"""Protocol interfaces for direct and future EPICS-backed devices."""

from __future__ import annotations

from typing import Protocol

from lapd_daq.models import AchievedPosition, CameraShot, PlannedPosition, ScopeShot


class ScopeDevice(Protocol):
    name: str

    def connect(self) -> None: ...
    def initialize(self) -> None: ...
    def arm(self) -> None: ...
    def acquire(self, shot_num: int) -> ScopeShot: ...
    def time_array(self): ...
    def metadata(self) -> dict[str, object]: ...
    def close(self) -> None: ...


class MotionDevice(Protocol):
    def connect(self) -> None: ...
    def move_to(self, position: PlannedPosition | None) -> AchievedPosition | None: ...
    def close(self) -> None: ...
    def metadata(self) -> dict[str, object]: ...


class CameraDevice(Protocol):
    def connect(self) -> None: ...
    def arm(self, shot_num: int) -> None: ...
    def complete(self, shot_num: int) -> CameraShot | None: ...
    def close(self) -> None: ...
    def metadata(self) -> dict[str, object]: ...


class TriggerDevice(Protocol):
    def connect(self) -> None: ...
    def trigger(self, shot_num: int) -> None: ...
    def close(self) -> None: ...
    def metadata(self) -> dict[str, object]: ...
